eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8881
spring:
  application:
    name: zuul
zuul:
  routes:
    account-service:
      path: /account-service/**
      serviceId: account-service